plugins/work_time/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match 'work_time', :to => 'work_time#index', :as => 'work_time', :via => [:get, :post], :defaults => { :format => 'html' }
match 'work_time/new', :to => 'work_time#new', :as => 'work_time_new', :via => [:get, :post]
match 'work_time/create', :to => 'work_time#create', :as => 'work_time_create', :via => [:get, :post]
match 'work_time/edit', :to => 'work_time#edit', :as => 'work_time_edit', :via => [:get, :post]
match 'work_time/update', :to => 'work_time#update', :as => 'work_time_update', :via => [:get, :post, :put]
match 'work_time/form', :to => 'work_time#form', :as => 'work_time_form', :via => [:get, :post]
match 'work_time/destroy', :to => 'work_time#destroy', :as => 'work_time_destroy', :via => [:get, :post]
match 'work_time/load_issues', :to => 'work_time#load_issues', :as => 'work_time_load_issues', :via => [:get, :post]
match 'work_time/include_issue', :to => 'work_time#include_issue', :as => 'work_time_include_issue', :via => [:get, :post]
match 'work_time/remove_issue', :to => 'work_time#remove_issue', :as => 'work_time_remove_issue', :via => [:get, :post]

plugins/work_time/app/helpers/work_time_helper.rb
module WorkTimeHelper
  def work_time_issue_link(issue)
    title = nil
    subject = nil
    text = "#{@trackers[issue.tracker_id]} ##{issue.id}"
		title = issue.subject.truncate(60)
    subject = issue.subject
	
    s = link_to(text, issue_url(issue),
                :class => issue.css_classes, :title => title)
    s << h(": #{subject}") if subject
    s
  end
  
  def csv_report
    cols = [l(:label_day_plural).capitalize] + render_days_csv
	
		Redmine::Export::CSV.generate do |csv|
      # csv header fields
      csv << cols
      
	  	@issues.each do |issue|
	    	unless @draw_projects.include?(issue.project_id)
					cols = [
					(@projects[issue.project_id] ? @projects[issue.project_id] : "")
					] + render_project_hours_csv(@projects[issue.project_id] ?  @projects[issue.project_id] : nil)

					@draw_projects << issue.project_id
				end
		
				cols = [
					issue.subject
				] + render_hours_csv(issue)
				csv << cols
			end
	  
	  csv << render_total_hours_csv
    end
	
  end
  
  def render_days_csv
		ths = []
		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			ths << date.day.to_s + " - " + day_short(date.cwday)
		end
		ths << l(:label_total)
		ths
  end
  
  def css_help
    colors = {
	  :holiday => "holiday-cell",
	  :non_working => "non-working-cell",
	  :today => "today-cell"
		}
		content_holiday = content_tag(:span, '&nbsp;&nbsp;&nbsp;'.html_safe,
																	:class => "#{colors[:holiday]}", :style => "border: #000 solid 1px;") + " #{l(:label_holiday_help)} "
		content_non_working = content_tag(:span, '&nbsp;&nbsp;&nbsp;'.html_safe,
																	:class => "#{colors[:non_working]}", :style => "border: #000 solid 1px;") + " #{l(:label_non_working_help)} "
		content_today = content_tag(:span, '&nbsp;&nbsp;&nbsp;'.html_safe,
																	:class => "#{colors[:today]}", :style => "border: #000 solid 1px;") + " #{l(:label_today_help)} "
    return content_holiday + content_non_working + content_today
  end
  
  def css_for_cell(date, issue =nil)
		colors = {
			:holiday => "holiday-cell",
			:non_working => "non-working-cell",
			:today => "today-cell",
			:not_leaf => "not-leaf-cell"
		}
		return colors[:not_leaf] if issue  && !issue.leaf?
		return colors[:today] if date == Date.today
		return colors[:non_working] if Setting.non_working_week_days.include?(date.cwday.to_s)
		return colors[:holiday] if @holidays.include?(date)
  end
  
  def render_issue_select
		select_tag "selected_issue_id",
		options_from_collection_for_select([], "id", "name", params[:issue_id]), 
		:id => :selected_issue_id, 
		:style => "width:100%; display: none;", 
		:include_blank => true,
		:onchange => "include_issue('#{work_time_include_issue_path}', '#{@date.strftime("%Y-%m-%d")}', '#{@user.id}', '#{(@project.nil? ? '' : @project.id)}')"
  end
  
  def render_project_select
		select_tag "selected_project_id",
		options_from_collection_for_select(@user_projects, "id", "name", params[:project_id]),
		:id => :selected_project_id,
		:style => "width:100%;",
		:include_blank => true,
		:onchange => "load_issues('#{work_time_load_issues_path}', '#{@date.strftime("%Y-%m-%d")}', '#{@user.id}')"
  end
  
  def render_total_hours_csv
    tds = []
		tds << l(:label_total)
		totals = {}
		total = 0
		@time_entries.each do |k, v|
			totals[k[0]] = 0 if totals[k[0]].nil?
			totals[k[0]] += v.round(2)
		end

		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			td = ""
			unless totals[date].nil?
				td = totals[date].round(2).to_s
			total += totals[date].round(2)
			else
				td = 0
			end
			tds << td
		end
	 
		tds << total

		tds
  end
  
  def render_total_hours_tr
    tds = ""
		tds << content_tag('td',
			"#{render_project_select}<br/> #{render_issue_select}".html_safe
		)
		totals = {}
		total = 0
		@time_entries.each do |k, v|
			totals[k[0]] = 0 if totals[k[0]].nil?
			totals[k[0]] += v.round(2)
		end

		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			td = ""
			unless totals[date].nil?
				td << content_tag("td", content_tag("span", totals[date].round(2)), :class => "td-total-day #{css_for_cell(date)}")
			total += totals[date].round(2)
			else
				td << content_tag("td", content_tag("span", 0), :class => "td-total-day #{css_for_cell(date)}")
			end
			tds << td
		end
		tds << content_tag("td", content_tag("span", "#{total}"), :class => "td-total-day")
		tds.html_safe
  end
  
  def render_remove_work_time(issue)
		(link_to_function image_tag('delete.png'), "remove_issue('#{work_time_remove_issue_path}', #{issue}, '#{@date.strftime("%Y-%m-%d")}', #{@user.id}, #{(@project.nil? ? 0 : @project.id)}, '#{l(:text_are_you_sure)}')").html_safe
  end
  
  def render_project_hours_csv(project)
		tds = []
		total = 0
		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			td = ""
			unless @project_time_entries[[date, project.id]].nil?
				total += @project_time_entries[[date, project.id]].to_f.round(2)
				td << @project_time_entries[[date, project.id]].round(2).to_s
			else
				td << 0
			end
			tds << td
		end
		tds << total
		tds
  end
  
  def render_project_hours_td(project)
		tds = ""
		total = 0
		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			td = ""
			unless @project_time_entries[[date, project.id]].nil?
				total += @project_time_entries[[date, project.id]].to_f.round(2)
				td << content_tag("td", @project_time_entries[[date, project.id]].round(2), :class => "td-project", :style => "text-decoration: underline;")
			else
				td << content_tag("td", 0, :class => "td-project")
			end

			tds << td
		end
		tds << content_tag("td", "#{total}", :class => "td-total-project td-project")
		tds.html_safe
  end
  
  def render_hours_td(issue)
    tds = ""
		total = 0

		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			td = ""
			unless @time_entries[[date, issue.id]].nil?
				total += @time_entries[[date, issue.id]].to_f.round(2)
			td << content_tag("td", @time_entries[[date, issue.id]].round(2),
			:class => "td-day td-active #{css_for_cell(date,issue)}",
			"data-empty".to_sym => false,
			"data-issue".to_sym => issue.id,
			"data-date".to_sym => date.strftime("%Y-%m-%d"),
			"data-user".to_sym => @user.id,
			"data-project".to_sym => (! @project.nil? ? 1 : 0),
			"data-leaf".to_sym => ( issue.leaf? ? 1 : 0),
			"data-url".to_sym => work_time_edit_path)
			else
				td << content_tag("td", "", :class => "td-day #{css_for_cell(date,issue)}",
			"data-empty".to_sym => true,
			"data-issue".to_sym => issue.id,
			"data-date".to_sym => date.strftime("%Y-%m-%d"),
			"data-user".to_sym => @user.id,
			"data-project".to_sym => (! @project.nil? ? 1 : 0),
			"data-leaf".to_sym => ( issue.leaf? ? 1 : 0),
			"data-url".to_sym => work_time_new_path)
			end
			tds << td
		end
		tds << content_tag("td", "#{total}", :class => "td-total-issue")
		tds.html_safe
  end
  
  def render_hours_csv(issue)
    tds = []
		total = 0
		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			td = ""
			unless @time_entries[[date, issue.id]].nil?
				total += @time_entries[[date, issue.id]].to_f.round(2)
			td << @time_entries[[date, issue.id]].round(2).to_s
			else
				td << ""
			end
			tds << td
		end
		tds << total
		tds
  end
  
  def render_days_th
		ths = ""
		@date.beginning_of_month.upto(@date.end_of_month) do |date|
			ths << content_tag('th', content_tag("div", date.day, :style => "font-weight: bold;") + content_tag("div", day_short(date.cwday), :style => "font-weight: bold;"), :class => "th-day")
		end
		ths << content_tag('th', "&nbsp;".html_safe, :class => "th-option")
		ths.html_safe
  end
  
  def render_month_th
		th = ""
			th << content_tag('tr',
			content_tag('th',
			render_previus_month_link.html_safe + month_name(@date.month) + " - #{@date.year}" + render_next_month_link.html_safe, :class => "th-month", :colspan => (2 + @date.end_of_month.day.to_i), :valign => "middle")
		)
		th.html_safe
  end
  
  def render_next_month_link
		"&nbsp;&nbsp;".html_safe + link_to(image_tag('right-arrow.png', :plugin => :work_time), work_time_path(params.merge(:date => @date.next_month).merge(:controller => :work_time).merge(:action => :index))).html_safe
  end
  
  def render_previus_month_link
		link_to(image_tag('left-arrow.png', :plugin => :work_time), work_time_path(params.merge(:date => @date.prev_month).merge(:controller => :work_time).merge(:action => :index))).html_safe + "&nbsp;&nbsp;".html_safe
  end
  
  def day_short(day)
    ::I18n.t('date.abbr_day_names')[day % 7].at(0..2)
  end
end

plugins/work_time/app/views/work_time/_form.html.erb
<div id="errorExplanation" style="display:none;"></div>
<div class="box tabular">
  <%= hidden_field_tag "format", "js" %>
  <% if @include_project %>
    <%= hidden_field_tag "project_id", @time_entry.project_id %>
  <% end %>
  <%= hidden_field_tag "date", @time_entry.spent_on %>
  <%= hidden_field_tag "user_id", @time_entry.user_id %>
  <% if params[:action] == "edit" || params[:action] == "form"  %>
    <%= hidden_field_tag "time_entry[id]", @time_entry.id, :id => "time_entry_id" %>
  <% end %>
  <%= hidden_field_tag "time_entry[project_id]", @time_entry.project_id %>
  <%= hidden_field_tag "time_entry[issue_id]", @time_entry.issue_id %>
  <%= hidden_field_tag "time_entry[user_id]", @time_entry.user_id %>
  
  <p><label for="time_entry_project"><%= l(:field_project) %></label><%= f.text_field :project, :size => 100, :required => false, :readonly => true %></p>
  <p><label for="time_entry_issue"><%= l(:field_issue) %></label><%= f.text_field :issue, :size => 100, :required => false, :readonly => true %></p>
  
  <p><label for="time_entry_spent_on"><%= l(:field_spent_on) %><span class="required"> *</span></label><%= f.text_field :spent_on, :size => 10, :required => true, :readonly => true %></p>
  
  <%= fields_for :issue, @time_entry.issue, { :builder => Redmine::Views::LabelledFormBuilder, :lang => current_language} do |issue| %>
	<% if @time_entry.issue.leaf? && Issue.use_field_for_done_ratio? %>
	  <p><%= issue.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r*10} %", (r*10).to_s] }) %></p>
	<% end %>
  <% end %>
  
  <p><label for="time_entry_hours"><%= l(:field_hours) %><span class="required"> *</span></label><%= f.text_field :hours, :size => 6, :required => true %></p>
  <p><label for="time_entry_comments"><%= l(:field_comments) %><span class="required"> *</span></label><%= f.text_field :comments, :size => 100, :maxlength => 1024 %></p>
  <p><label for="time_entry_activity_id"><%= l(:field_activity) %><span class="required"> *</span></label><%= f.select :activity_id, activity_collection_for_select_options(@time_entry), :required => true %></p>
  <% @time_entry.custom_field_values.each do |value| %>
    <p><%= custom_field_tag_with_label :time_entry, value %></p>
  <% end %>
</div>

plugins/work_time/app/views/work_time/_table.html.erb
<table class="list work-time">
  <thead>
	<%= render_month_th %>
	<tr>
	  <!--<th class="project"><%#= l(:field_project) %></th>-->
 	  <th class="issue"><%= l(:label_day_plural).capitalize %></th>
	  <%= render_days_th %>
	</tr>
  </thead>
  <tbody>
	<% @issues.each do |issue|%>
	  <% unless @draw_projects.include?(issue.project_id) %>
		<tr>
		  <td class="project td-project">
		    <%= @projects[issue.project_id] ? link_to_project(@projects[issue.project_id]) : raw("&nbsp;") %>
	      </td>
		  <%= render_project_hours_td((@projects[issue.project_id] ?  @projects[issue.project_id] : nil)) %>
		</tr>
		<% @draw_projects << issue.project_id %>
	  <% end %>
	  <tr>
	    <!--<td class="project">
		  <%#= @projects[issue.project_id] ? link_to_project(@projects[issue.project_id]) : raw("&nbsp;") %>
	    </td>-->
	    <td class="issue">
		  <div style="margin-left: 10px;" class="tooltip">
			<%= work_time_issue_link(issue) %>
			<!--<span class="tip"><%#= render_issue_tooltip issue %></span>-->
			<% if @work_time_issues.include?(issue.id) %>
			  <%= render_remove_work_time(issue.id) %>
		    <% end %>
		  </div>
	    </td>
		<%= render_hours_td(issue) %>
	  </tr>
	<% end %>
	<tr><%= render_total_hours_tr %></tr>
  </tbody>
</table>
<%= javascript_include_tag :work_time, :plugin => 'work_time' %>

plugins/work_time/app/views/work_time/create.js.erb
<% unless @time_entry.valid? %>
  $("#errorExplanation").html('<%= raw(escape_javascript(@time_entry.errors.full_messages.join(', '))) %>');
  $("#errorExplanation").show();
<% else %>
  $("#errorExplanation").html('');
  $("#errorExplanation").hide();
  $('#table').html('<%= escape_javascript(render :partial => 'table') %>');
  $("#work-time-popup").dialog("close");
<% end %>

plugins/work_time/app/views/work_time/destroy.js.erb
$('#table').html('<%= escape_javascript(render :partial => 'table') %>');
$("#work-time-popup").dialog("close");

plugins/work_time/app/views/work_time/edit.html.erb
<h3 class="title"><%= l(:project_module_work_time) %></h3>
<table class="list">
  <% @time_entries.each do |time_entry| %>
  <tr>
    <td style="width: 20%;"><%= format_date(time_entry.spent_on) %></td>
	<td style="width: 10%;"><%= time_entry.hours %></td>
	<td style="text-align: left;"><%= time_entry.comments.truncate(50) %></td>
	<td class="buttons">
	  <% if User.current.allowed_to?(:edit_time_entries, time_entry.project) %>
		<%= link_to_function("".html_safe, "edit_time_entry('#{time_entry.id}', '#{work_time_form_path}', '#{@include_project ? 1 : 0}')", :class => "icon icon-edit", :alt=> l(:button_edit), :style => " padding-right: 0px") %>	  
		<%= link_to_function "".html_safe, "destroy_time_entry('#{time_entry.id}', '#{work_time_destroy_path}', '#{@include_project ? 1 : 0}', '#{l(:text_are_you_sure)}', '#{@include_project ? time_entry.project_id : ''}', '#{time_entry.user_id}', '#{time_entry.spent_on}')", :class => "icon icon-del", :alt=> l(:button_delete), :style => " padding-right: 0px" %>
	  <% end %>
	</td>
  </tr>
  <% end %>
</table>
&nbsp;
<div id="time_entry_form">
<%= form_for @time_entry, :url => work_time_create_path, :id => "time-entry-form" do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create), :onclick => "save_time_entry(); return false;" %>
<% end %>
</div>

plugins/work_time/app/views/work_time/form.html.erb
<%= form_for @time_entry, :url => work_time_update_path, :id => "time-entry-form" do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_edit), :onclick => "update_time_entry(); return false;" %>
<% end %>

plugins/work_time/app/views/work_time/include_issue.html.erb
$("#errorExplanation").html('');
$("#errorExplanation").hide();
$('#table').html('<%= escape_javascript(render :partial => 'table') %>');

plugins/work_time/app/views/work_time/index.html.erb
<%= stylesheet_link_tag(:work_time, :plugin => 'work_time', :media => 'all') %>

<%= title l(:label_work_time), "#{month_name(@date.month)} - #{@date.year}" %>

<%= form_tag({ :controller => 'work_time', :action => 'index', :project_id => @project.nil? ? nil : @project.id },
            :method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>
	<hr/>
	<%if params[:project_id]%>
	  <%= hidden_field_tag :project_id, params[:project_id] %>
	<% end %>

    </div>
    <p class="buttons">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    &nbsp;
	<%= hidden_field_tag 'date', @date.strftime("%Y-%m-%d"), :onchange => "this.form.submit(); return false;", :style => "display: none;"%><%= calendar_for('date') %>
	&nbsp;&nbsp;
	<%= css_help %>
	</p>
  </div>
<% end %>

<%= error_messages_for 'query' %>

<div id="table">
  <%= render :partial => "table" %>
</div>

<div id="work-time-popup" style="display:none">
  
</div>

<% other_formats_links do |f| %>
  <%= f.link_to 'CSV', :url => params.merge({:format => :csv}) %>
<% end %>

plugins/work_time/app/views/work_time/load_issues.js.erb
$('#selected_issue_id').html('<%= escape_javascript(content_tag("option") + options_from_collection_for_select(@issues, "id", "id_and_subject")) %>');
$('#selected_issue_id').css("display", "block");

plugins/work_time/app/views/work_time/new.html.erb
<h3 class="title"><%= l(:project_module_work_time) %></h3>
<%= form_for @time_entry, :url => work_time_create_path, :html => {:html => {:id => "time-entry-form"}} do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create), :onclick => "save_time_entry(); return false;" %>
<% end %>

plugins/work_time/app/views/work_time/remove_issue.js.erb
$("#errorExplanation").html('');
$("#errorExplanation").hide();
$('#table').html('<%= escape_javascript(render :partial => 'table') %>');

plugins/work_time/app/views/work_time/update.js.erb
<% unless @time_entry.valid? %>
  $("#errorExplanation").html('<%= raw(escape_javascript(@time_entry.errors.full_messages.join(', '))) %>');
  $("#errorExplanation").show();
<% else %>
  $("#errorExplanation").html('');
  $("#errorExplanation").hide();
  $('#table').html('<%= escape_javascript(render :partial => 'table') %>');
  $("#work-time-popup").dialog("close");
<% end %>