plugins/modifications/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/helps_aig', :to => redirect('ayudas/index.html'), :as => 'helps_aig'
resources :project_queries, :except => [:show]
match '/context_menu/projects/', :to => 'context_menus#projects', :as => 'projects_context_menu', :via => [:get, :post]
match '/get_done_ratio/get_done_ratio/:project_id', :to => 'issues#get_done_ratio', :as => 'issue_get_done_ratio', :via => [:post]
match '/issues/validate_recurrence', :to => 'issues#validate_recurrence', :action => 'validate_recurrence', :as => 'validate_recurrence', :via => [:get, :post]
match '/issues/validate_recurrence_for_committee', :to => 'issues#validate_recurrence_for_committee', :action => 'validate_recurrence_for_committee', :as => 'validate_recurrence_for_committee', :via => [:get, :post]
match '/issues/table_row', :to => 'issues#table_row', :action => 'table_row', :as => 'issue_table_row', :via => [:get, :post]
match '/issues/committee_data', :to => 'issues#committee_data', :action => 'committee_data', :as => 'issue_committee_data', :via => [:get, :post]
match '/issues/get_direction', :to => 'issues#get_direction', :action => 'get_direction', :as => 'issue_get_direction', :via => [:get, :post]
match '/issues/load_responsables', :to => 'issues#load_responsables', :action => 'load_responsables', :as => 'issue_load_responsables', :via => [:get, :post]
match '/issues/trackers_for_import', :to => 'issues#trackers_for_import', :action => 'trackers_for_import', :as => 'issue_trackers_for_import', :via => [:get, :post]
match '/issues/attributes_for_import', :to => 'issues#attributes_for_import', :action => 'attributes_for_import', :as => 'issue_attributes_for_import', :via => [:get, :post]
match '/user/import', :to => 'users#import', :action => 'import', :as => 'users_import', :via => [:get, :post]
match '/user/import_positions', :to => 'users#import_positions', :action => 'import_positions', :as => 'users_import_positions', :via => [:get, :post]
resources :issues do
  resources :checklists, :only => [:index, :create]
end

resources :checklists, :only => [:destroy, :update, :show] do
  member do
    put :done
  end
end

resources :project_templates

plugins/modifications/app/views/projects/_form.html.erb
<%= error_messages_for 'project' %>

<div class="box tabular">
<!--[form:project]-->
<p><%= f.text_field :name, :required => true, :size => 60 %></p>

<p><%= f.text_area :description, :rows => 3, :class => 'wiki-edit' %></p>


<p><%= f.text_field :identifier, 
	:required => true, :size => 60, 
	:disabled => @project.identifier_frozen?, 
	:maxlength => Project::IDENTIFIER_MAX_LENGTH, 
	:readonly => @project.is_template?%>
<% unless @project.identifier_frozen? %>
  <em class="info"><%= l(:text_length_between, :min => 1, :max => Project::IDENTIFIER_MAX_LENGTH) %> <%= l(:text_project_identifier_info).html_safe %></em>
<% end %></p>
<p><%= f.text_field :homepage, :size => 60 %></p>
<p><%= f.check_box :is_public %></p>

<p style="display:none;"><%= f.check_box :is_template %></p>

<p><%= f.select :project_type_id, ProjectType.all.collect {|p| [ p.name, p.id ] }, :include_blank => false, :required => true %></p>

<% unless @project.allowed_parents.compact.empty? || @project.is_template? %>
    <p><%= label(:project, :parent_id, l(:field_parent)) %><%= parent_project_select_tag(@project) %></p>
<% end %>

<% if @project.safe_attribute? 'inherit_members' %>
<p><%= f.check_box :inherit_members %></p>
<% end %>

<% if @project.safe_attribute?('default_version_id') && (default_version_options = project_default_version_options(@project)).present? %>
  <p><%= f.select :default_version_id, project_default_version_options(@project), :include_blank => true %></p>
<% end %>

<%= wikitoolbar_for 'project_description' %>

<% @project.custom_field_values.each do |value| %>
  <p><%= custom_field_tag_with_label :project, value %></p>
<% end %>
<%= call_hook(:view_projects_form, :project => @project, :form => f) %>
</div>

<% if @project.new_record? %>
<fieldset class="box tabular"><legend><%= l(:label_module_plural) %></legend>
	<label class="floating"><%= check_box_tag 'project[overview]', 1, true -%>
		<%= l(:label_overview) %></label>
	<label class="floating"><%= check_box_tag 'project[activity]', 1, true -%>
		<%= l(:label_activity) %></label>
<% Redmine::AccessControl.available_project_modules.select{|it| it != :gantt}.each do |m| %>
    <label class="floating">
    <%= check_box_tag 'project[enabled_module_names][]', m, @project.module_enabled?(m), :id => "project_enabled_module_names_#{m}" %>
    <%= l_or_humanize(m, :prefix => "project_module_") %>
    </label>
<% end %>
<%= hidden_field_tag 'project[enabled_module_names][]', '' %>
</fieldset>
<% end %>

<% if @project.new_record? || @project.module_enabled?('issue_tracking') %>
<% unless @trackers.empty? %>
<fieldset class="box tabular" id="project_trackers"><legend><%=l(:label_tracker_plural)%></legend>
<% @trackers.each do |tracker| %>
    <label class="floating">
    <%= check_box_tag 'project[tracker_ids][]', tracker.id, @project.trackers.to_a.include?(tracker), :id => nil %>
    <%= tracker %>
    </label>
<% end %>
<%= hidden_field_tag 'project[tracker_ids][]', '' %>
</fieldset>
<% end %>

<% unless @issue_custom_fields.empty? %>
<fieldset class="box tabular" id="project_issue_custom_fields"><legend><%=l(:label_custom_field_plural)%></legend>
<% @issue_custom_fields.each do |custom_field| %>
    <label class="floating">
  <%= check_box_tag 'project[issue_custom_field_ids][]', custom_field.id, (@project.all_issue_custom_fields.include? custom_field),
        :disabled => (custom_field.is_for_all? ? "disabled" : nil),
        :id => nil %>
  <%= custom_field_name_tag(custom_field) %>
  </label>
<% end %>
<%= hidden_field_tag 'project[issue_custom_field_ids][]', '' %>
</fieldset>
<% end %>
<% end %>
<!--[eoform:project]-->

<% unless @project.identifier_frozen? %>
  <% content_for :header_tags do %>
    <%= javascript_include_tag 'project_identifier' %>
  <% end %>
<% end %>

<% if !User.current.admin? && @project.inherit_members? && @project.parent && User.current.member_of?(@project.parent) %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $("#project_inherit_members").change(function(){
        if (!$(this).is(':checked')) {
          if (!confirm("<%= escape_javascript(l(:text_own_membership_delete_confirmation)) %>")) {
            $("#project_inherit_members").attr("checked", true);
          }
        }
      });
    });
  <% end %>
<% end %>

<%= javascript_tag do %>
$(document).ready(function() {
  $('#project_enabled_module_names_issue_tracking').on('change', function(){
    if ($(this).prop('checked')){
      $('#project_trackers, #project_issue_custom_fields').show();
    } else {
      $('#project_trackers, #project_issue_custom_fields').hide();
    }
  }).trigger('change');
});
<% end %>

plugins/modifications/app/views/projects/_list.html.erb
<% curr_parents = [] %>
<%= form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params) %>
<div class="autoscroll">
<table class="list projects">
<thead>
  <tr>
    <% @query.inline_columns.each do |column| %>
      <%= column_header(column) %>
    <% end %>
   
  </tr>
</thead>
<tbody>
<% parents = [] %>
<% hiddens = [] %>

<% projects.each do |project| -%>
  <% if project.parent.nil? %>
  
    <% parents << project.id %>
	
  <% elsif ! parents.include?(project.parent.id) && project.ancestors.size <= 0 && @query.is_tree %>
	<%= render :partial => "parent", :locals => {:project => project.parent}%>
	<% parents << project.parent.id %>

  <% end %>
  <% if project.curr_ancestors.size > 0 && @query.is_tree %>
    <% hiddens << project.id %> 
  <% end %>
  <tr class="project <%= cycle("odd", "even") %> hascontextmenu <%= project.css_classes %> <%= project.tree_class %> <%= project.curr_ancestors.size > 0 && @query.is_tree ? "idnt idnt-#{project.curr_ancestors.size}" : nil %>" 
	style="<%= (hiddens.include?(project.parent ? project.parent_id : 0)) ? "display: none;" : nil %>">
    <td class="checkbox hide-when-print" style="display:none;"><%= check_box_tag("id", project.id, false, :id => nil) %></td>
    <%= raw @query.inline_columns.map {|column| 
		if project.descendants.size > 0
			if column.name.to_s == 'name' && @query.is_tree
			  curr_parents << project.id
				"<td class=\"#{column.css_classes}\" style=\"padding-left: #{(project.curr_ancestors.size > 0 && @query.is_tree && hiddens ? project.curr_ancestors.size + 0.5 : 0.5)}em;\">#{content_tag(:span, '&nbsp;'.html_safe, :class => 'toggle-multiselect hidde_tr', "data-id".to_sym => project.id, "data-display".to_sym => 0)}&nbsp;#{column_content(column, project)}</td>"
			elsif column.name.to_s == 'name'
				"<td style='padding-left: 0em;' class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
			else
			  "<td class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
			end
		elsif project.parent.nil?
			column.name.to_s == 'name' ? "<td class=\"#{column.css_classes}\" style=\"padding-left: #{(project.curr_ancestors.size > 0 && @query.is_tree ? project.curr_ancestors.size + 0.5 : 0.5)}em;\">#{column_content(column, project)}</td>" : "<td class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
		else
			column.name.to_s == 'name' ? "<td class=\"#{column.css_classes}\" style=\"padding-left: #{(project.curr_ancestors.size > 0 && @query.is_tree && curr_parents.include?(project.parent.id) ? project.curr_ancestors.size + 0.5 : 0.5)}em;\"><span>#{column_content(column, project)}</span></td>" : "<td class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
		end
	}.join %>
  </tr>
<% end -%>
</tbody>
</table>
</div>
<% end -%>
<script>
$( document ).ready(function() {
    parents = <%= curr_parents.to_json %>;
	for(i = 0; i < parents.length; i++){
	  $(".project-" + parents[i]).css("display", "none");
	}
});
</script>
<%= context_menu projects_context_menu_path %>
<% content_for :header_tags do %>

<style>
.idnt {
	
}
</style>
<script>
$(document).on('click','.hidde_tr',function(e){		
	if($(this).data("display") == "0" || $(this).data("display") == "0"){
	  $(".project-" + $(this).data("id")).css("display", "table-row");
	  $(".project-" + $(this).data("id")).data("display", 1);
	  $(this).data("display", 1);
	}
	else{
	  $(".project-" + $(this).data("id")).css("display", "none");
	  $(".project-" + $(this).data("id")).data("display", 0);
	  $(this).data("display", 0);
	}
});
</script>
<% end %>

plugins/modifications/app/views/projects/_parent.html.erb
<tr class="project <%= cycle("odd", "even") %> hascontextmenu <%= project.css_classes %> <%= project.tree_class %> <%= project.ancestors.size > 0 && @query.is_tree ? "idnt idnt-#{project.ancestors.size}" : nil %>" 
  style="<%= project.ancestors.size > 0 && @query.is_tree ? "display: none;" : nil %>">
  <td class="checkbox hide-when-print" style="display:none;"><%= check_box_tag("id", project.id, false, :id => nil) %></td>
  <%= raw @query.inline_columns.map {|column| 
	if project.descendants.size > 0
	  if column.name.to_s == 'name' && @query.is_tree
		"<td class=\"#{column.css_classes}\" style=\"padding-left: #{(project.ancestors.size > 0 && @query.is_tree ? project.ancestors.size + 0.5 : 0)}em;\">#{content_tag(:span, '&nbsp;'.html_safe, :class => 'toggle-multiselect hidde_tr', "data-id".to_sym => project.id, "data-display".to_sym => 0)}&nbsp;#{column_content(column, project)}</td>"
	  else
		"<td class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
	  end
	elsif project.parent.nil?
	  column.name.to_s == 'name' ? "<td class=\"#{column.css_classes}\" style=\"padding-left: #{(project.ancestors.size > 0 && @query.is_tree ? project.ancestors.size + 0.5 : 0)}em;\">#{column_content(column, project)}</td>" : "<td class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
	else
	  column.name.to_s == 'name' ? "<td class=\"#{column.css_classes}\" style=\"padding-left: #{(project.ancestors.size > 0 && @query.is_tree ? project.ancestors.size + 0.5 : 0)}em;\"><span>#{column_content(column, project)}</span></td>" : "<td class=\"#{column.css_classes}\">#{column_content(column, project)}</td>"
	end
  }.join %>
</tr>

plugins/modifications/app/views/projects/_sidebar.html.erb
<h3><%= l(:label_project_plural) %></h3>

<%= render_sidebar_project_queries %>

plugins/modifications/app/views/projects/index.html.erb
<% content_for :header_tags do %>
    <%#= auto_discovery_link_tag(:atom, {:action => 'index', :format => 'atom', :key => User.current.rss_key}) %>
<% end %>

<div class="contextual">
	
	
    <%= link_to(l(:label_project_new), {:controller => 'projects', :action => 'new'}, :class => 'icon icon-add') + ' | ' if User.current.allowed_to?(:add_project, nil, :global => true) %>
    <%= link_to(l(:label_project_templates), {:controller => 'project_templates', :action => 'index'}, :class => 'icon icon-project-templates') + ' | ' if User.current.allowed_to?(:add_project, nil, :global => true) %>
	<%= link_to(l(:label_issue_view_all), issues_path, :class => 'icon icon-time-entry-list') + ' |' if User.current.allowed_to?(:view_issues, nil, :global => true) %>
    <%#= link_to(l(:label_overall_spent_time), time_entries_path, :class => 'icon icon-total-time') + ' |' if User.current.allowed_to?(:view_time_entries, nil, :global => true) %>
	<%= link_to l(:label_overall_activity),
                { :controller => 'activities', :action => 'index',
                  :id => nil }, :class => 'icon icon-all-activity' %>
	
	<% if !@query.new_record? && @query.editable_by?(User.current) %>
		<%= raw " | " + link_to(l(:button_edit), {:controller => :project_queries, :action => :edit, :id => @query.id}, :class => 'icon icon-edit') %>
		<%= raw " | " + delete_link({:controller => :project_queries, :action => :destroy, :id => @query.id}) %>
	<% end %>
</div>

<h2><%= @query.new_record? ? l(:label_project_plural) : h(@query.name) %></h2>

<%= form_tag({ :controller => 'projects', :action => 'index'},
            :method => :get, :id => 'query_form') do %>
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content" class="hide-when-print">
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'project_queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>
    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <!--<tr>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
          </tr>-->
          <tr>
            <!--<td><%= l(:button_show) %></td>
            <td><%= available_block_columns_tags(@query) %></td>-->
          </tr>
        </table>
      </div>
    </fieldset>
    </div>
    <p class="buttons hide-when-print">

    <%= link_to_function l(:button_apply), '$("#query_form").submit();', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
      <% allowed_to_save = false %>
      <% if @project %>
        <% allowed_to_save = User.current.allowed_to?(:save_queries, @project, :global => true) %>
      <% else %>
        <% Project.visible.each do |project| %>
          <% if User.current.allowed_to?(:save_queries, project, :global => true) %>
            <% allowed_to_save = true %>
          <% end %>
        <% end %>
      <% end %>
      <% if allowed_to_save %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : url_for({:controller => :project_queries, :action => :new}) }').submit()",
                             :class => 'icon icon-save' %>
    <%  end %>
    </p>
<% end %>



<%= error_messages_for 'query' %>
<% if @query.valid? %>
<% if @projects.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
<%= render :partial => 'projects/list', :locals => {:projects => @projects, :query => @query} %>
<span class="pagination"><%= pagination_links_full @project_pages, @project_count %></span>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'CSV', :url => params, :onclick => "showModal('csv-export-options', '330px'); return false;" %>
<% end %>

<div id="csv-export-options" style="display:none;">
  <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
  <%= form_tag(params.merge({:format => 'csv',:page=>nil}), :method => :get, :id => 'csv-export-form') do %>
  <p>
    <label><%= radio_button_tag 'columns', '', true %> <%= l(:description_selected_columns) %></label><br />
    <label><%= radio_button_tag 'columns', 'all' %> <%= l(:description_all_columns) %></label>
  </p>
  <p>
    <label><%= check_box_tag 'description', '1', @query.has_column?(:description) %> <%= l(:field_description) %></label><br/>
  </p>
  <p class="buttons">
    <%= submit_tag l(:button_export), :name => nil, :onclick => "hideModal(this);" %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
  <% end %>
</div>


<% end %>

<%= call_hook(:view_issues_index_bottom, { :issues => @issues, :project => @project, :query => @query }) %>

<% content_for :sidebar do %>
    <%= render :partial => 'sidebar' %>
<% end %>

<% html_title(l(:label_project_plural)) -%>

plugins/modifications/app/views/projects/show.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_subprojects, @project) %>
    <%= link_to l(:label_subproject_new), new_project_path(:parent_id => @project), :class => 'icon icon-add' %>
  <% end %>
  <% if User.current.allowed_to?(:close_project, @project) %>
    <% if @project.active? %>
      <%= link_to l(:button_close), close_project_path(@project), :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-lock' %>
    <% else %>
      <%= link_to l(:button_reopen), reopen_project_path(@project), :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-unlock' %>
    <% end %>
  <% end %>
</div>

<h2><%=l(:label_overview)%></h2>

<% unless @project.active? %>
  <p class="warning"><span class="icon icon-lock"><%= l(:text_project_closed) %></span></p>
<% end %>

<div class="splitcontentleft">
  <%# if @project.description.present? %>
  <!--<div class="wiki">
    <%#= textilizable @project.description %>
  </div>-->
  <%# end %>
  <% if @project.homepage.present? || @subprojects.any? || @project.visible_custom_field_values.any?(&:present?) %>
  <ul>
  <% unless @project.project_type.blank? %>
      <li><span class="label"><%=l(:field_project_type)%>:</span> <%= @project.project_type %></li>
  <% end %>
  <% unless @project.homepage.blank? %>
    <li><span class="label"><%=l(:field_homepage)%>:</span> <%= link_to @project.homepage, @project.homepage %></li>
  <% end %>
  <% if @subprojects.any? %>
    <li><span class="label"><%=l(:label_subproject_plural)%>:</span>
      <%= @subprojects.collect{|p| link_to p, project_path(p)}.join(", ").html_safe %></li>
  <% end %>
  <% render_custom_field_values(@project) do |custom_field, formatted| %>
    <li><span class="label"><%= custom_field.name %>:</span> <%= formatted %></li>
  <% end %>
  </ul>
  <% end %>
  
  <div class="description box">
    <% if @project.description.present? %>
      <h3><%=l(:field_description)%></h3>
      <!--<div class="wiki" id="div_description_short">
        <%#= truncate(@project.description, :length => 150) %><%#= link_to_function(image_tag('zoom_in.png', :alt => l(:button_expand_all)), "show_description('div_description_short', 'div_description_long');") if @project.description.length > 150 %>
      </div>
      <div class="wiki" id="div_description_long" style="display: none;">
      <%#= @project.description %><%#= link_to_function(image_tag('zoom_out.png', :alt => l(:button_collapse_all)), "hide_description('div_description_long', 'div_description_short');") %>-->
      <div class="wiki">
        <%= textilizable @project.description %>
      </div>
    <% end %>
  </div>
  
  <% if User.current.allowed_to?(:view_issues, @project) %>
  <div class="issues box">
    <h3><%=l(:label_issue_tracking)%></h3>
    <% if @trackers.present? %>
    <table class="list issue-report">
      <thead>
        <tr>
          <th></th>
          <th><%=l(:label_open_issues_plural)%></th>
          <th><%=l(:label_closed_issues_plural)%></th>
          <th><%=l(:label_total)%></th>
        </tr>
      </thead>
      <tbody>
      <% @trackers.each do |tracker| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td class="name">
            <%= link_to tracker.name, project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id) %>
          </td>
          <td>
            <%= link_to @open_issues_by_tracker[tracker].to_i, project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id) %>
          </td>
          <td>
            <%= link_to (@total_issues_by_tracker[tracker].to_i - @open_issues_by_tracker[tracker].to_i), project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id, :status_id => 'c') %>
          </td>
          <td>
            <%= link_to @total_issues_by_tracker[tracker].to_i, project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id, :status_id => '*') %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <% end %>
    <p>
      <%= link_to l(:label_issue_view_all), project_issues_path(@project, :set_filter => 1) %>
      <% if User.current.allowed_to?(:view_calendar, @project, :global => true) %>
        | <%= link_to l(:label_calendar), project_calendar_path(@project) %>
      <% end %>
      <% if User.current.allowed_to?(:view_gantt, @project, :global => true) %>
        | <%= link_to l(:label_gantt), project_gantt_path(@project) %>
      <% end %>
    </p>
  </div>
  <% end %>
  <%= call_hook(:view_projects_show_left, :project => @project) %>
</div>

<div class="splitcontentright">
  <%= render :partial => 'members_box' %>
  
  <%= render :partial => 'indicators', :locals => { :project =>  @project }  %>
  
  <% if @news.any? && authorize_for('news', 'index') %>
  <div class="news box">
    <h3><%=l(:label_news_latest)%></h3>
    <%= render :partial => 'news/news', :collection => @news %>
    <p><%= link_to l(:label_news_view_all), project_news_index_path(@project) %></p>
  </div>
  <% end %>
  <%= call_hook(:view_projects_show_right, :project => @project) %>
</div>

<% content_for :sidebar do %>
  <% if User.current.allowed_to?(:view_time_entries, @project) %>
  <h3><%= l(:label_spent_time) %></h3>
  <% if @total_hours.present? %>
    <p><span class="icon icon-time"><%= l_hours(@total_hours) %></span></p>
  <% end %>
  <p style="text-align: center;">
    <% if User.current.allowed_to?(:log_time, @project) %>
      <%= link_to l(:button_log_time), new_project_time_entry_path(@project) %> |
    <% end %>
    <%= link_to(l(:label_details), project_time_entries_path(@project)) %> |
    <%= link_to(l(:label_report), report_project_time_entries_path(@project)) %>
  </p>
  <% end %>
  
  <div id="gauge_cpi" class="googauges" align="center" style="display: none"></div>
  <div id="gauge_spi" class="googauges" align="center" style="display: none"></div>
<%= call_hook(:view_projects_show_sidebar_bottom, :project => @project) %>
<% end %>

<% content_for :header_tags do %>
<%= javascript_include_tag "https://www.google.com/jsapi" %>
<%= javascript_tag do %>
  google.load("visualization", "1", {packages:["corechart"]});
  google.load('visualization', '1', {packages: ['gauge']});
<% end %>
<%= javascript_tag do %>
  function drawCpi() {
    // Create and populate the data table.
    var data_gauge = new google.visualization.arrayToDataTable([
      ['Label', 'Value'],
      ['CPI', <%= @project.cpi %>]
    ]);
    var options_g = {
      redFrom: 0, redTo: 0.85,
      yellowFrom:0.85, yellowTo: 1,
      greenFrom:1, greenTo:2,
      minorTicks:5,
      min:0, max:2
    };
    // Create and draw the visualization.
    var gauge= new google.visualization.Gauge(document.getElementById("gauge_cpi"));
    gauge.draw(data_gauge, options_g);
  }

  function drawSpi() {
    // Create and populate the data table.
    var data_gauges = new google.visualization.arrayToDataTable([
      ['Label', 'Value'],
      ['SPI', <%= @project.spi %>]
    ]);
    var options_gs = {
      redFrom: 0, redTo: 0.85,
      yellowFrom:0.85, yellowTo: 1,
      greenFrom:1, greenTo:2,
      minorTicks:5,
      min:0, max:2
    };
    // Create and draw the visualization.
    var gauge= new google.visualization.Gauge(document.getElementById("gauge_spi"));
    gauge.draw(data_gauges, options_gs);
  }
  
<% end %>
<script>
function show_description(hide, show){
  $("#" + hide).css("display", "none");
  $("#" + show).css("display", "block");
}

function hide_description(hide, show){
  $("#" + hide).css("display", "none");
  $("#" + show).css("display", "block");
}
</script>
<%= auto_discovery_link_tag(:atom, {:controller => 'activities', :action => 'index', :id => @project, :format => 'atom', :key => User.current.rss_key}) %>
<% end %>
<script>
drawCpi();
drawSpi();
</script>
<% html_title(l(:label_overview)) -%>
<script>
    $(document).ready(function() {
        $('#sidebar').addClass('sidebar_hidden');
        $('#content').addClass('sidebar_hidden');
        $('#hideSidebarButton').addClass('sidebar_hidden');
        $('#hideSidebarButton').css('display', 'none')
    });
</script>