plugins/resources/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources 'user_calendars'

match '/user_calendars/get_calendar_table', :to => 'user_calendars#get_calendar_table', :action => 'get_calendar_table', :as => 'get_calendar_table', :via => [:get, :post]
match '/planning/:id/simulate', :to => 'planning#simulate', :action => 'simulate', :as => 'planning_simulate', :via => [:get, :post]
match '/resources/projects', :to => 'resources#projects', :action => 'projects', :as => 'project_resources', :via => [:get, :post]
match '/resources/:project_id/issues', :to => 'resources#issues', :action => 'issues', :as => 'issue_resources', :via => [:get, :post]


scope '(projects/:project_id)' do
  resource :easy_resources, :controller => 'easy_resources', :only => [:index, :items_data] do
    member do
      get 'issues'
      get 'projects'
      #put 'relation/:id(.:format)', :to => 'easy_gantt#change_issue_relation_delay'
    end
  end
end

plugins/resources/app/models/user_calendar.rb
class UserCalendar < ActiveRecord::Base
  include Redmine::SafeAttributes
  
  safe_attributes 'name'
  
  validates_presence_of :name
  
  has_many :user_calendar_hours, :dependent => :destroy
  
  validate :hours_numbers
  
  def hours_numbers
    errors.add(:base, l(:error_user_calendar_hours)) unless user_calendar_hours.any?
  end
  
  def self.default
    UserCalendar.find(Setting.default_calendar) rescue nil
  end
  
  def to_s
	self.name
  end
  
end

plugins/resources/app/controllers/user_calendars_controller.rb
class UserCalendarsController < ApplicationController
  
  before_filter :require_admin
  
  before_filter :find_user_calendar
  
  helper 'sort'
  
  include SortHelper
  
  layout "admin"
  
  def index
    sort_init 'name', 'asc'
    sort_update %w(name created_on)

    @limit = per_page_option

    scope = UserCalendar.where(nil)
    scope = scope.where("name LIKE '%#{params[:name]}%'") if params[:name].present?

    @user_calendar_count = scope.count
    @user_calendar_pages = Paginator.new @user_calendar_count, @limit, params['page']
    @offset ||= @user_calendar_pages.offset
    @user_calendars =  scope.order(sort_clause).limit(@limit).offset(@offset).to_a

    respond_to do |format|
      format.html {
        render :layout => !request.xhr?
      }
    end
  end
  
  def create
	@user_calendar.safe_attributes = params[:user_calendar].permit(:name)
	
	make_days_ranges(params[:calendar_hours]).each do |k, v|
	  @user_calendar.user_calendar_hours << UserCalendarHour.new(
		:init => v.min,
		:due => v.max,
		:total_hours => v.max - v.min, 
		:week_day => k
	  )
	end
	
    if @user_calendar.save
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_create)
          redirect_to user_calendars_path
        }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
      end
    end
  end
  
  def edit
    @user_calendar_hours = hours_for_edit(@user_calendar.user_calendar_hours)
  end
  
  def get_calendar_table
	@user_calendar = UserCalendar.default if @user_calendar.new_record?
    @user_calendar_hours = hours_for_edit(@user_calendar.user_calendar_hours)
  end
  
  def hours_for_edit(hours)
	days = {}
	hours.each do |hour|
	  days[hour.week_day] ||= []
	  (hour.init..hour.due).each do |h|
	    days[hour.week_day] << h.to_i
	  end
	end
	days
  end
  
  def new
  end
  
  def update
	@user_calendar.safe_attributes = params[:user_calendar].permit(:name)
	@user_calendar.user_calendar_hours.destroy_all
	make_days_ranges(params[:calendar_hours]).each do |k, v|
	  @user_calendar.user_calendar_hours << UserCalendarHour.new(
		:init => v.min,
		:due => v.max,
		:total_hours => v.max - v.min, 
		:week_day => k
	  )
	end
	
    if @user_calendar.save
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_update)
		  redirect_to user_calendars_path
        }
      end
    else
      respond_to do |format|
        format.html { render :action => :edit }
      end
    end
  end
  
  def destroy
    @user_calendar.destroy
    respond_to do |format|
      format.html { 
		flash[:notice] = l(:notice_successful_delete)
		redirect_back_or_default(user_calendars_path) 
	  }
    end
  end
  
  private 
  
  def find_user_calendar
	begin
		@user_calendar = UserCalendar.find(params[:id])
	rescue
		@user_calendar = UserCalendar.new
	end
  end
  
  def make_days_ranges(days)
	week_days = []
	Rack::Utils.parse_nested_query(days).each do |k, v|
	  next if v.empty?
	  element = 0
	  tmp = []
	  elements = v.split(',')
	  elements.each do |h|
		tmp << h.to_i 
		unless elements.include?((h.to_i + 1).to_s)
		  week_days << [k, tmp]
		  tmp = [] 
		end
	  end
	end
	week_days
  end
  
end

plugins/resources/app/helpers/user_calendars_helper.rb
module UserCalendarsHelper
  def calendar_header()
	day_start_of_week = Date.today.beginning_of_week
	day_end_of_week = Date.today.end_of_week
	ths = [content_tag("th","")]
	day_start_of_week.upto(day_end_of_week) do |date|
	  ths << content_tag("th", day_name(date.wday).at(0..2), :class => "")
	end
	content_tag("tr",ths.join("").html_safe)
  end
  
  def calendar_body(hours={})
	trs = []
	day_start_of_week = Date.today.beginning_of_week
	day_end_of_week = Date.today.end_of_week
	
	start_time = Setting.start_calendar_time.to_i
	start_time -= 1 unless start_time == 0
	
	ending_time = Setting.end_calendar_time.to_i
	ending_time += 1 unless ending_time == 24 

	(start_time..ending_time).each do |hour|
	  tds = []
	  tds << content_tag("td", "#{hour}:00", 
						:style=>"padding: 0px; margin:0px; font-size: 10px;")
	  day_start_of_week.upto(day_end_of_week) do |date|
	    tds << content_tag("td", "", :data => {:hour => "#{hour}", :day => date.cwday}, 
			:style=>"padding: 0px; margin:0px; font-size: 10px;", 
			:class => "tr-selectable day-#{date.cwday} #{class_selectable(hour, date.cwday, hours)}")
      end
	  trs << content_tag("tr", tds.join.html_safe, :class => cycle("odd", "even"))
	end
	trs.join.html_safe
  end

  def calendar_body_members(hours={})
	trs = []
	day_start_of_week = Date.today.beginning_of_week
	day_end_of_week = Date.today.end_of_week

	min = 24
	max = 0

	hours.each do |day, hours|
		min = hours.min
		max = hours.max
	end 

	min -= 1 unless min <= Setting.start_calendar_time.to_i
	max += 1 unless max >= Setting.end_calendar_time.to_i

	(min..max).each do |hour|
	  tds = []
	  tds << content_tag("td", "#{hour}:00", 
						:style=>"padding: 0px; margin:0px; font-size: 10px;")
	  day_start_of_week.upto(day_end_of_week) do |date|
	    tds << content_tag("td", "", :data => {:hour => "#{hour}", :day => date.cwday}, 
			:style=>"padding: 0px; margin:0px; font-size: 10px;", 
			:class => "tr-selectable day-#{date.cwday} #{class_selectable(hour, date.cwday, hours)}")
      end
	  trs << content_tag("tr", tds.join.html_safe, :class => cycle("odd", "even"))
	end
	trs.join.html_safe
  end
  
  def calendar_widget(hours={})
	content_tag("table", calendar_header + calendar_body(hours), :class => "list user-calendar-table")
  end

  def calendar_widget_members(hours={})
	content_tag("table", calendar_header + calendar_body_members(hours), :class => "list user-calendar-table")
  end
  
  def draw_hours(calendar)
	html = []
    calendar.user_calendar_hours.each do |cal|
	  html << day_name(cal.week_day) + " #{text_hour(cal.init)}:00 - #{text_hour(cal.due)}:00"
	end
	html.join(', ').html_safe
  end
  
  def text_hour(hour)
    hours = [
		1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
	]
	hours[hour.to_i]
  end
  
  def class_selectable(hour, day, hours)
	if ! hours[day.to_i]
	  return ""
	elsif ! hours[day.to_i].include?(hour)
	  return ""
	else
	  return "ui-selected"
	end
  rescue
	return ""
  end
  
  def hours_for_edit(hours)
	days = {}
	hours.each do |hour|
	  days[hour.week_day] ||= []
	  (hour.init..hour.due).each do |h|
	    days[hour.week_day] << h.to_i
	  end
	end
	days
  end
end

plugins/resources/app/views/user_calendars/_form.html.erb
<%= error_messages_for 'user_calendar' %>


<!--[form:user_calendar]-->
<div class="box tabular">
  <%= hidden_field_tag 'calendar_hours', '' %>
  <p><%= f.text_field :name, :required => true %></p>
  <div class="div-user-calendar-label">
	<label for="user_calendar_availability">
	  <%= l(:field_availability) %>
	  <span class="required"> *</span>
	</label>
  </div>
  
  <div class="div-user-calendar">
    <%= calendar_widget(@user_calendar_hours) %>
  </div>
  
</div>
<div style="clear:left;"></div>
<!--[eoform:user_calendar]-->
<%= javascript_tag do %>

<% end %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag(:user_calendar, :plugin => 'resources', :media => 'all') %>
  <%= stylesheet_link_tag("jquery-ui", :plugin => 'resources', :media => 'all') %>
  <%= javascript_include_tag("jquery-ui", :plugin => 'resources') %> 
<% end %>
<script>

$(".user-calendar-table").selectable({
  filter: ".tr-selectable", 
  stop: function() {
	set_data();
  }
});

function set_data(){
  data = [];
  data[1] = [];
  data[2] = [];
  data[3] = [];
  data[4] = [];
  data[5] = [];
  data[6] = [];
  data[7] = [];
  $( ".ui-selected").each(function() {
    data[parseInt($(this).data("day"))].push($(this).data("hour"));
	url = Object.keys(data).map(function(k) {
      return encodeURIComponent(k) + '=' + encodeURIComponent(data[k])
    }).join('&');
    $("#calendar_hours").val(url);
  });
}

set_data();
</script>

plugins/resources/app/views/user_calendars/edit.html.erb
<div class="contextual">
<%= delete_link user_calendar_path(@user_calendar) %>
</div>

<%= title [l(:label_user_calendar_plural), user_calendars_path], @user_calendar.name %>

<%= labelled_form_for @user_calendar, :url => user_calendar_path(@user_calendar), :method => :put do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p>
    <%= submit_tag l(:button_update) %>
  </p>
<% end %>

<% html_title l(:label_user_calendar) %>

plugins/resources/app/views/user_calendars/get_calendar_table.js.erb
$('.div-user-calendar').html('<%= escape_javascript(calendar_widget_members(@user_calendar_hours)) %>');

plugins/resources/app/views/user_calendars/index.html.erb
<div class="contextual">
<%= link_to(l(:label_user_calendars_new), new_user_calendar_path, :class => 'icon icon-add') %></div>

<h2><%=l(:label_user_calendar_plural)%></h2>

<%= form_tag(user_calendars_path, :method => :get) do %>
<fieldset><legend><%= l(:label_filter_plural) %></legend>

<label for='name'><%= l(:field_name) %>:</label>
<%= text_field_tag 'name', params[:name], :size => 30 %>
<%= submit_tag l(:button_apply), :class => "small", :name => nil %>
<%= link_to l(:button_clear), user_calendars_path, :class => 'icon icon-reload' %>
</fieldset>
<% end %>
&nbsp;

<div class="autoscroll">

<% if @user_calendars.any? %>

<table class="list">
  <thead><tr>
  <%= sort_header_tag('name', :caption => l(:field_name)) %>
  <%= sort_header_tag('created_on', :caption => l(:field_created_on)) %>
  <th><%= l(:field_user_calendar_hours) %></th>
	<th></th>
  </tr></thead>
  <tbody>
<% for user_calendar in @user_calendars -%>
  <tr class="<%= cycle("odd", "even") %>">
  <td class="name"><%= link_to user_calendar.name, edit_user_calendar_path(user_calendar) %></td>

  <td class="created_on"><%= format_time(user_calendar.created_on) %></td>
  <td class="user_calendar_hours"><%= draw_hours(user_calendar) %></td>
  <td class="buttons">
    <%= delete_link user_calendar_path(user_calendar, :back_url => request.original_fullpath) %>
  </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<span class="pagination"><%= pagination_links_full @user_calendar_pages, @user_calendar_count %></span>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% html_title(l(:label_user_calendar_plural)) -%>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag(:user_calendar, :plugin => 'resources', :media => 'all') %>
<% end %>

plugins/resources/app/views/user_calendars/new.html.erb
<%= title [l(:label_user_calendar_plural), user_calendars_path], l(:label_user_calendars_new) %>

<%= labelled_form_for @user_calendar, :url => user_calendars_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p>
    <%= submit_tag l(:button_create) %>
  </p>
<% end %>


<% html_title l(:label_user_calendar) %>